#include "Dio_confg.h"

DIO_confg_t Peripherals[num_of_pins]=
{
		{PORT_A,PIN1,OUTPUT,NA,LOW,INITIALIZED},
		{PORT_A,PIN2,OUTPUT,NA,LOW,INITIALIZED},
		{PORT_A,PIN3,OUTPUT,NA,LOW,INITIALIZED},

		{PORT_A,PIN4,OUTPUT,NA,LOW,INITIALIZED},
		{PORT_A,PIN5,OUTPUT,NA,LOW,INITIALIZED},
		{PORT_A,PIN6,OUTPUT,NA,LOW,INITIALIZED},
		{PORT_A,PIN7,OUTPUT,NA,LOW,INITIALIZED},

		{PORT_C,PIN0,OUTPUT,NA,LOW,INITIALIZED},
};

